# Redis Server
redis:
  image: redis
  volumes:
    - /mydir/database/redis/data:/data
  restart: always
#wechat app
profile:
  image: ynuae/wx-card-info
  ports:
    - "40001:40001"
  links:
    - redis:redis
  environment:
    - QYH_CORPID
    - QYH_SECRET
    - PROFILE_TOKEN
    - PROFILE_AESKEY
    - PROFILE_AGENTID
    - REDIS_HOST
    - WEBSERVICE_URL
    - WEBSERVICE_ID
    - WEBSERVICE_KEY
  restart: always
